[package]
name = "psilo-vfs-pathmacro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
regex = "1.5"
once_cell = "1.8"
unicode-normalization = "0.1.19"
syn = "1.0"
quote = "1.0"
